/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.Random;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }


    public static int [] roll(int num){
        Random diceValue = new Random();
        int [] arr = new int[num];
        for(int i = 0 ; i < num ; i++){
            int randomValue = diceValue.nextInt(6)+1;
            arr[i] = randomValue;
        }
        return arr;

    }

    public static boolean containsDuplicates(int [] arr){
        int value ;
        for(int i = 0 ; i < arr.length ; i++){
            value = arr[i];
            for(int j = i +1 ; i < arr.length ; i++){
                if(arr[j] == value){
                    return false;
                }
            }
        }
        return  true;
    }

    public static double calculateAverage(double [] arr){
        double sum =0;
        int count=0;
        double avg;
        for(int i = 0; i < arr.length ; i++){
            sum += arr[i];
            count ++;
        }
        avg = sum/count;
        return avg;
    }

    public static int[] lowestAverage(int[][] arr) {
        double average = 0 , lowestAverage = Integer.MAX_VALUE;
        int lowestAverageArr[] = arr[0];
        for (int i = 0; i < arr.length; i++) {
            average = 0;
            for (int j = 0 ; j < arr[i].length ; j++){
                average+=arr[i][j];
            }
            average /= arr[i].length;
            if(average < lowestAverage) {
                lowestAverage = average;
                lowestAverageArr = arr[i];
            }

        }
        return lowestAverageArr;
    }
}
