/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;
import java.util.*;
import java.util.ArrayList;

public class User extends Review{
    String name;

    public void searchReviews(List<Review> reviewUser,String n) {

        for (Review element : reviewUser) {

            if (element.toString().contains(n)) {
                System.out.println("We are Sorry "+n+", you can't add multiple reviews");
            }
            else {
                Restaurant review=new Restaurant("Eater's","JD");
                review.addReview(2.1,"The order was missing! :(","Yousef");
            }
        }
    }
}