/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;

public class User extends Review{
    String name;

    public void findReviews(ArrayList<Review> reviewUser,String n) {
        for (Review element : reviewUser) {

            if (element.toString().contains(n)) {
                System.out.println("We are Sorry "+n+", you can't add multiple reviews");
            }
            else {
                Review review=new Review();
                review.updateRate(2.8);
            }
        }
    }

    @Override
    public String toString() {
        return "Customer{" +
                "rate=" + rate +
                ", body='" + body + '\'' +
                ", author='" + author + '\'' +
                '}';
    }
}